# Generated by Django 2.1.7 on 2019-05-27 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=200)),
                ('air_date', models.DateField(default=django.utils.timezone.now)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('number_of_ratings', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('season', models.IntegerField()),
                ('imdb_episode_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imdb_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_data.Show'),
        ),
    ]
