# Generated by Django 2.1.7 on 2019-05-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_data', '0002_show_title_slugged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title_slugged',
            field=models.SlugField(unique=True),
        ),
    ]
