# Generated by Django 2.1.7 on 2019-05-28 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tv_data', '0003_auto_20190527_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster_url',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='rated',
            field=models.CharField(default='TV-MA', max_length=10),
        ),
        migrations.AddField(
            model_name='show',
            name='released',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
